### PR TITLE
Humans: The Dickening

### PR DESCRIPTION
**Pull request by FriedrichRatzel**
## About The Pull Request

This adds a bit of overlay shitfuckery to the humans, namely - gives players an ability to choose overlays for tits, genitalia and butt. For now, only tits have multiple selection (ranging from "small" to "big"). The other two options allow to choose between "Vanilla (no sprite)" and the new sprite.

Menu is accessible through verbs: IC -> Genitalia selection. For now, players can switch their sprites mid-round - because of the following reasons.
- I have no idea how to add this selection to the character setup menu without breaking modular logic
- Enlargement and related stuff can require swapping sprites mid-round.

I think that changing boob sprite mid-round can result in immersion-breaking moments. Yet, Keila assured me that it's fine. Anyway, if you have any ideas - I'm more welcome to discuss alternative approaches.

Regarding code. Icons are cached the first time they are created, so this has minimal impact on the server's perfomance. 
Overlays are hidden, when a uniform or a suit is equipped. Although I'm pretty sure that some gloves/shoes/backpacks can overlap, it is nearly impossible to test every clothing in a reasonable amount of time. At the end of the day, players can hide overlays themselves in case butt shows up from under a backpack.

<details>
  <summary>Demonstration ahead</summary>

https://github.com/user-attachments/assets/18e8670a-fd9f-40e3-bfff-90c06579879c

</details>

## Why It's Good For The Game

Moar sprites, better immersion 'n stuff.

## Changelog

:cl: Keila-coon and a passing-by coder
add: Added genitalia overlay system. Accessible through IC -> Genital Selection
/:cl:

### CODE REVIEW

**Comment by EaglePhntm** [comment]
Did you make this be saved to preferences so it sticks round to round?

**Comment by Keila-coon** [comment]
> Did you make this be saved to preferences so it sticks round to round?

It does not save through rounds, genitals settings need to be reapplied every round. If we wish to have something like that in the character creation we would also like to remake the entire character system to move to greyscale sprites for example.

**Comment by EaglePhntm** [comment]
> > Did you make this be saved to preferences so it sticks round to round?
> 
> It does not save through rounds, genitals settings need to be reapplied every round. If we wish to have something like that in the character creation we would also like to remake the entire character system to move to greyscale sprites for example.

not really, can just make the vars save to the prefs of the player, search for xgender and find my xeno gender thing.

**Comment by EaglePhntm** [comment]
vagina addition would be epic but i'll merge this now

**Pull request merged**
